sequenceDiagram
User->>Inventory-app: load the main page to view all items
Inventory-app->>User: view all items
User->>Inventory-app: request to view one item
Inventory-app->>User: view one item
User->>Inventory-app: request to add one item
Inventory-app->>User: add one item
User->>Inventory-app: request to delete one item
Inventory-app->>User: delete one item
User->>Inventory-app: request to update one item
Inventory-app->>User: update one item